apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kafkacat
  name: kafkacat
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kafkacat
  strategy: {}
  template:
    metadata:
      labels:
        run: kafkacat
    spec:
      containers:
      - image: edenhill/kafkacat:1.6.0
        name: kafkacat
        command:
          - sh
          - -c
          - "exec tail -f /dev/null"
