apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
spec:
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
      - name: schema-registry
        image: confluentinc/cp-schema-registry:6.0.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        command: ["/bin/bash"]
        args: ["-c","unset SCHEMA_REGISTRY_PORT; /etc/confluent/docker/run"]
        env:
          - name: SCHEMA_REGISTRY_HOST_NAME
            value: "schema-registry"
          - name: SCHEMA_REGISTRY_LISTENERS
            value: "http://0.0.0.0:8081"
          - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
            value: "broker:29092"
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
spec:
  type: NodePort
  selector:
    app: schema-registry
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
