apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
spec:
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "Password!"
        - name: restart
          value: "unless-stopped"
        volumeMounts:
        - name: hostvolume
          mountPath: /var/opt/mssql/data
      volumes:
      - name: hostvolume
        hostPath: 
          path: /Users/falmeida/env_dev/k8s_sql_volume
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
spec:
  type: LoadBalancer
  selector:
    app: mssql
  ports:
  - port: 1433
    targetPort: 1433

