apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-center
spec:
  selector:
    matchLabels:
      app: control-center
  template:
    metadata:
      labels:
        app: control-center
    spec:
      containers:
      - name: control-center
        image: confluentinc/cp-enterprise-control-center:6.0.0
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 9021
        env:
          - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
            value: "broker:29092"
          - name: CONTROL_CENTER_CONNECT_CLUSTER
            value: "kafka-connect:8083"
          - name: CONTROL_CENTER_KSQL_KSQLDB1_URL
            value: "http://kubernetes.docker.internal:30088"
          - name: CONTROL_CENTER_KSQL_KSQLDB1_ADVERSTISED_URL
            value: "http://kubernetes.docker.internal:8088"
          - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
            value: "http://schema-registry:8081"
          - name: CONTROL_CENTER_REPLICATION_FACTOR
            value: "1"
          - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITION
            value: "1"
          - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
            value: "1"          
          - name: CONFLUENT_METRICS_TOPIC_REPLICATION
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: control-center
spec:
  type: NodePort
  selector:
    app: control-center
  ports:
  - port: 9021
    protocol: TCP
    targetPort: 9021
    name: http
    nodePort: 30008