apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: confluentinc/cp-kafka:6.0.0
        ports:
        - containerPort: 29092
        env:
          - name: KAFKA_BROKER_ID 
            value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT 
            value: "zookeeper:2181"
          - name: KAFKA_LISTENERS 
            value: "INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:30092"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "INTERNAL://broker:29092,EXTERNAL://localhost:30092"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP 
            value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME 
            value: "INTERNAL"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE 
            value: "false"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR 
            value: "1"
          - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR 
            value: "1"
          - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR 
            value: "1"
          - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS 
            value: "100"
          - name: KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL
            value: "http://schema:registry:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  selector:
    app: broker
  ports:
  - port: 29092
    targetPort: 29092



