apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksqldb
spec:
  selector:
    matchLabels:
      app: ksqldb
  template:
    metadata:
      labels:
        app: ksqldb
    spec:
      containers:
      - name: ksqldb
        image: confluentinc/ksqldb-server:0.15.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8088
        env:
        - name: KSQL_LISTENERS
          value: "http://0.0.0.0:8088"
        - name: KSQL_BOOTSTRAP_SERVERS
          value: "broker:29092"
        - name: KSQL_KSQL_SERVICE_ID
          value: "confluent_rmoff_01"
        - name: KSQL_KSQL_SCHEMA_REGISTRY
          value: "http://schema-registry:8081"
        - name: KSQL_KSQL_HIDDEN_TOPICS
          value: "'^_.*'"
        - name: KSQL_KSQL_CONNECT_URL
          value: "http://kafka-connect:8083"
---
apiVersion: v1
kind: Service
metadata:
  name: ksqldb
spec:
  type: NodePort
  selector:
    app: ksqldb
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 8088
    nodePort: 30088
